
    - name: Install aptitude
      apt: pkg=aptitude update_cache=yes
      become: yes

    - name: Apt update/upgrade
      apt: upgrade=yes update_cache=yes
      become: yes

    - name: Install tmux terminal multiplexer
      apt: pkg=tmux
      become: yes

    - name: Install required packages
      apt: pkg={{ item }}
      become: yes
      with_items:
      - git
      - automake
      - autoconf
      - pkg-config
      - libcurl4-openssl-dev
      - libjansson-dev
      - libssl-dev
      - libgmp-dev

    - name: Get veriumMiner
      git: repo=https://github.com/effectsToCause/veriumMiner dest=~/veriumMiner

    - name: autogen
      command: ./autogen.sh chdir=~/veriumMiner

    - name: configure
      command: ./configure CFLAGS="-march=native" --with-crypto --with-curl chdir=~/veriumMiner

    - name: make
      command: make chdir=~/veriumMiner
