
    - name: Install aptitude
      apt: pkg=aptitude update_cache=yes
      become: yes

    - name: Apt update/upgrade
      apt: upgrade=yes update_cache=yes
      become: yes

    - name: Install tmux terminal multiplexer
      apt: pkg=tmux
      become: yes

    - name: Install required packages
      apt: pkg={{ item }}
      become: yes
      with_items:
      - libxrender1
      - libxcomposite1
      - libxslt1-dev
      - libqrencode-dev
      - libgstreamer0.10-0
      - libgstreamer-plugins-base0.10-0

    - name: Download CUDA repository .deb
      get_url: url=http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb dest=/tmp/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
      register: get_deb_result
      until: get_deb_result | succeeded
      retries: 3
      delay: 1

    - name: Install CUDA repository
      apt: deb=/tmp/cuda-repo-ubuntu1604_8.0.61-1_amd64.deb
      become: yes

    - name: Install CUDA
      apt: pkg=cuda update_cache=yes
      become: yes

    - name: Download Verium .run
      get_url: url=http://www.vericoin.info/downloads/Verium_1.0.4_64bit.run dest=~/Verium_1.0.4_64bit.run mode=a+x
      register: get_url_result
      until: get_url_result | succeeded
      retries: 3
      delay: 1

    - name: Verium .run
      command: ./Verium_1.0.4_64bit.run chdir=~/

    - name: Configure Verium
      lineinfile: dest=~/Verium_1.0.4_64bit/verium.conf line="{{ item }}"
      with_items:
      - gen=1
      - daemon=1
